# This rule is not used by the project cloudfront-tenant-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cloudfront.cloudfront-tenant-operator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudfront-tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: distributiontenant-editor-role
rules:
- apiGroups:
  - cloudfront.cloudfront-tenant-operator.io
  resources:
  - distributiontenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudfront.cloudfront-tenant-operator.io
  resources:
  - distributiontenants/status
  verbs:
  - get
