# This rule is not used by the project cloudfront-tenant-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cloudfront-tenant-operator.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudfront-tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: distributiontenant-viewer-role
rules:
- apiGroups:
  - cloudfront-tenant-operator.io
  resources:
  - distributiontenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudfront-tenant-operator.io
  resources:
  - distributiontenants/status
  verbs:
  - get
